### PR TITLE
Fix sourcemap detection

### PR DESCRIPTION
**Pull request by crgwbr**
This pull request fixes grunt-exorcise to work with the latest version of Browserify (>=10.2.0).

### CODE REVIEW

**Comment by mikefrey** [comment]
:+1:  Thanks!

**Comment by mikefrey** [comment]
Published in `grunt-exorcise@2.0.0`

**Comment by crgwbr** [comment]
:+1: Thanks for merging!

**Comment by HenriqueSilverio** [comment]
Thanks! :+1:

**Pull request merged**
